Последняя нерабочая версия
lp-scrumpy/backend pull request #10
Opened 2022-03-29 15:46 UTC by elijah-radchenko

2022-03-29 15:51 UTC, elijah-radchenko commented
Я решил сначала с первой табличкой разобраться. Пользователи. остальные закомментил

2022-03-30 09:58 UTC, vppuzakov requested changes
🔴  поправить repr -  это фукнция должна быть внутри класса

2022-03-30 09:58 UTC, vppuzakov commented on backend/models.py
> +    children = relationship("Estimate")
💡 не уверен, что пригодится это поле, ну ок - пусть будет

2022-03-30 09:58 UTC, vppuzakov commented on backend/models.py
> +    children = relationship('Task')
👍

2022-03-30 09:58 UTC, vppuzakov commented on backend/models.py
> +def __repr__(self):
🔴  def `__repr__` почему не внутри класса? Это касается всех классов

2022-03-30 10:03 UTC, elijah-radchenko commented on backend/models.py
> +def __repr__(self):
это всё vs code. шутка.

2022-03-30 16:54 UTC, vppuzakov approved these changes
👍 approve + merge

2022-03-30 17:04 UTC, merged